CREATE TABLE `sources` (`id` text PRIMARY KEY NOT NULL, `name` text NOT NULL, `kind` text NOT NULL, `adapter` text NOT NULL, `endpoint` text, `config` text DEFAULT '{}' NOT NULL, `cost_tier` text DEFAULT 'free' NOT NULL, `trust_score` integer DEFAULT 50 NOT NULL, `enabled` integer DEFAULT true NOT NULL, `last_collected_at` text, `created_at` text NOT NULL, `updated_at` text NOT NULL);
CREATE INDEX `sources_kind_idx` ON `sources` (`kind`);
CREATE INDEX `sources_enabled_idx` ON `sources` (`enabled`);
CREATE TABLE `events` (`id` text PRIMARY KEY NOT NULL, `slug` text NOT NULL, `title` text NOT NULL, `summary` text NOT NULL, `category` text NOT NULL, `status` text DEFAULT 'candidate' NOT NULL, `confidence` integer DEFAULT 0 NOT NULL, `heat_score` real DEFAULT 0 NOT NULL, `velocity_score` real DEFAULT 0 NOT NULL, `market_score` real DEFAULT 0 NOT NULL, `trust_score` real DEFAULT 0 NOT NULL, `cross_source_score` real DEFAULT 0 NOT NULL, `relevance_score` real DEFAULT 0 NOT NULL, `novelty_score` real DEFAULT 0 NOT NULL, `symbols` text DEFAULT '[]' NOT NULL, `tags` text DEFAULT '[]' NOT NULL, `facts` text DEFAULT '[]' NOT NULL, `unknowns` text DEFAULT '[]' NOT NULL, `market_snapshot` text DEFAULT '{}' NOT NULL, `first_seen_at` text NOT NULL, `occurred_at` text, `created_at` text NOT NULL, `updated_at` text NOT NULL);
CREATE UNIQUE INDEX `events_slug_idx` ON `events` (`slug`);
CREATE INDEX `events_heat_idx` ON `events` (`heat_score`);
CREATE INDEX `events_status_idx` ON `events` (`status`);
CREATE INDEX `events_category_idx` ON `events` (`category`);
CREATE TABLE `evidence` (`id` text PRIMARY KEY NOT NULL, `event_id` text NOT NULL REFERENCES `events`(`id`) ON DELETE cascade, `source_id` text REFERENCES `sources`(`id`) ON DELETE set null, `kind` text NOT NULL, `title` text NOT NULL, `url` text, `author` text, `excerpt` text NOT NULL, `published_at` text, `captured_at` text NOT NULL, `content_hash` text, `trust_score` integer DEFAULT 50 NOT NULL, `is_primary` integer DEFAULT false NOT NULL, `raw` text DEFAULT '{}' NOT NULL, `created_at` text NOT NULL, `updated_at` text NOT NULL);
CREATE INDEX `evidence_event_idx` ON `evidence` (`event_id`);
CREATE INDEX `evidence_source_idx` ON `evidence` (`source_id`);
CREATE TABLE `accounts` (`id` text PRIMARY KEY NOT NULL, `name` text NOT NULL, `platform` text DEFAULT 'binance_square' NOT NULL, `specialty` text NOT NULL, `tone` text NOT NULL, `topic_rules` text DEFAULT '[]' NOT NULL, `min_confidence` integer DEFAULT 75 NOT NULL, `daily_limit` integer DEFAULT 20 NOT NULL, `enabled` integer DEFAULT true NOT NULL, `credentials_ref` text, `created_at` text NOT NULL, `updated_at` text NOT NULL);
CREATE INDEX `accounts_platform_idx` ON `accounts` (`platform`);
CREATE INDEX `accounts_enabled_idx` ON `accounts` (`enabled`);
CREATE TABLE `content_drafts` (`id` text PRIMARY KEY NOT NULL, `event_id` text NOT NULL REFERENCES `events`(`id`) ON DELETE cascade, `account_id` text REFERENCES `accounts`(`id`) ON DELETE set null, `format` text NOT NULL, `status` text DEFAULT 'draft' NOT NULL, `headline` text NOT NULL, `body` text NOT NULL, `disclosure` text, `angle` text NOT NULL, `source_citation_ids` text DEFAULT '[]' NOT NULL, `version` integer DEFAULT 1 NOT NULL, `generated_by` text DEFAULT 'template-v1' NOT NULL, `approved_by` text, `approved_at` text, `created_at` text NOT NULL, `updated_at` text NOT NULL);
CREATE INDEX `drafts_event_idx` ON `content_drafts` (`event_id`);
CREATE INDEX `drafts_status_idx` ON `content_drafts` (`status`);
CREATE TABLE `assets` (`id` text PRIMARY KEY NOT NULL, `event_id` text REFERENCES `events`(`id`) ON DELETE cascade, `draft_id` text REFERENCES `content_drafts`(`id`) ON DELETE cascade, `kind` text NOT NULL, `status` text DEFAULT 'planned' NOT NULL, `url` text, `storage_key` text, `alt_text` text NOT NULL, `width` integer, `height` integer, `metadata` text DEFAULT '{}' NOT NULL, `created_at` text NOT NULL, `updated_at` text NOT NULL);
CREATE INDEX `assets_event_idx` ON `assets` (`event_id`);
CREATE INDEX `assets_draft_idx` ON `assets` (`draft_id`);
CREATE TABLE `publication_jobs` (`id` text PRIMARY KEY NOT NULL, `draft_id` text NOT NULL REFERENCES `content_drafts`(`id`) ON DELETE cascade, `account_id` text NOT NULL REFERENCES `accounts`(`id`) ON DELETE cascade, `status` text DEFAULT 'queued' NOT NULL, `scheduled_at` text NOT NULL, `attempts` integer DEFAULT 0 NOT NULL, `idempotency_key` text NOT NULL, `platform_post_id` text, `platform_url` text, `last_error` text, `published_at` text, `created_at` text NOT NULL, `updated_at` text NOT NULL);
CREATE UNIQUE INDEX `publication_idempotency_idx` ON `publication_jobs` (`idempotency_key`);
CREATE INDEX `publication_status_schedule_idx` ON `publication_jobs` (`status`,`scheduled_at`);
CREATE TABLE `audit_logs` (`id` text PRIMARY KEY NOT NULL, `actor` text NOT NULL, `action` text NOT NULL, `entity_type` text NOT NULL, `entity_id` text NOT NULL, `before` text, `after` text, `request_id` text, `created_at` text NOT NULL);
CREATE INDEX `audit_entity_idx` ON `audit_logs` (`entity_type`,`entity_id`);
CREATE INDEX `audit_created_idx` ON `audit_logs` (`created_at`);
